spring.application.name=forum
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:usuarios
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

server.port = 8080

# Judge0 API Configuration
judge0.api.key=${JUDGE0_API_KEY:a0901aebcbmsh9f8745681497560p1c9e05jsn6a7d905366c}
judge0.api.host=${JUDGE0_API_HOST:judge0-ce.p.rapidapi.com}
judge0.api.url=${JUDGE0_API_URL:https://judge0-ce.p.rapidapi.com/submissions?base64_encoded=false&wait=true}
